export const shooterSprites = {
  ship: '/phithuyen/processed/player-ship.png',
  boss: '/boss/processed/1781075547319_781607616673702390_781607616673702390_462ca4f6b3f0c05f56092e7c86b84da1.png',
  miniScout: '/boss/bossmini/processed/void_phantom_-_power.png',
  miniScoutAlt: '/boss/bossmini/processed/bossnbv_2.png',
  miniBlade: '/boss/bossmini/processed/sandfield_lord.png',
  miniHeavy: '/boss/bossmini/processed/ancient_giant.png',
  hazard: '/missions/shooter/nasa-assets/hazard-asteroid.jpg',
  power: '/boss/vatpham/processed/vatpham-items.png',
};

const missionPresets = {
  sun: { objective: 'Survive the corona ignition zone', targetKills: 30, targetScore: 4600, timeLimit: 90, hazardRate: 1.5, bossHp: 72, pattern: 'flare' },
  mercury: { objective: 'Survive the solar flare belt', targetKills: 22, targetScore: 2600, timeLimit: 78, hazardRate: 1.1, bossHp: 46, pattern: 'flare' },
  venus: { objective: 'Clear the acid cloud front', targetKills: 24, targetScore: 2800, timeLimit: 82, hazardRate: 1.25, bossHp: 50, pattern: 'poison' },
  earth: { objective: 'Defend orbit and remove debris', targetKills: 24, targetScore: 3000, timeLimit: 84, hazardRate: 1, bossHp: 48, pattern: 'debris' },
  mars: { objective: 'Break through the dust trench', targetKills: 26, targetScore: 3200, timeLimit: 84, hazardRate: 1.2, bossHp: 54, pattern: 'dust' },
  jupiter: { objective: 'Stabilize the storm stream', targetKills: 28, targetScore: 3600, timeLimit: 88, hazardRate: 1.35, bossHp: 62, pattern: 'storm' },
  saturn: { objective: 'Survive the ring shard lane', targetKills: 28, targetScore: 3500, timeLimit: 88, hazardRate: 1.45, bossHp: 58, pattern: 'rings' },
  uranus: { objective: 'Correct the tilted ice orbit', targetKills: 30, targetScore: 3900, timeLimit: 92, hazardRate: 1.45, bossHp: 64, pattern: 'ice' },
  neptune: { objective: 'Escape the abyss tempest', targetKills: 32, targetScore: 4200, timeLimit: 94, hazardRate: 1.6, bossHp: 70, pattern: 'tempest' },
};

const withMission = (id, config) => ({
  ...config,
  mission: missionPresets[id],
});

export const weaponTypes = {
  pulse: {
    id: 'pulse',
    name: 'Pulse Cannon',
    label: 'Pulse',
    cooldown: 0.14,
    damage: 1,
    speed: 760,
    spread: [0],
  },
  triBeam: {
    id: 'triBeam',
    name: 'Tri-Beam Array',
    label: 'Tri-Beam',
    cooldown: 0.2,
    damage: 1,
    speed: 710,
    spread: [-12, 0, 12],
  },
  seeker: {
    id: 'seeker',
    name: 'Seeker Missile',
    label: 'Seeker',
    cooldown: 0.34,
    damage: 3,
    speed: 540,
    spread: [0],
    homing: true,
  },
};

export const upgradeTypes = {
  shield: { id: 'shield', name: 'Aegis Shield', description: '+34 shield at launch' },
  engine: { id: 'engine', name: 'Ion Engine', description: '+16% movement control' },
  overdrive: { id: 'overdrive', name: 'Overdrive Core', description: 'Start with powered weapon' },
};

export const planetShooterConfig = {
  sun: withMission('sun', {
    title: 'Sun Corona Breaker',
    subtitle: 'Xuyên qua vùng nhật hoa và né bão plasma',
    background: '/planets/sun.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-1.jpg',
    palette: ['#fff1a8', '#ff9f1c', '#ef4444'],
    accent: '#fff1a8',
    enemyColor: '#ffd166',
    bossColor: '#ef4444',
    hazardColor: '#fed7aa',
    shotColors: { scout: '#fff1a8', scoutAlt: '#ffd166', blade: '#ff9f1c', heavy: '#fb7185', boss: '#ef4444' },
    enemyLabel: 'Plasma wraith',
    bossName: 'Corona Star Tyrant',
    terrain: 'solar corona ignition zone',
    difficulty: 1.5,
  }),
  mercury: withMission('mercury', {
    title: 'Mercury Solar Run',
    subtitle: 'Vượt qua đá nóng và vệ binh Mặt Trời',
    background: '/planets/mercury.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-1.jpg',
    palette: ['#ffd166', '#f97316', '#6b5d4f'],
    accent: '#fff1a8',
    enemyColor: '#ffb84d',
    bossColor: '#ff6b35',
    hazardColor: '#ffedd5',
    shotColors: { scout: '#ffd166', scoutAlt: '#ff9f1c', blade: '#ff4d00', heavy: '#fff1a8', boss: '#ff6b35' },
    enemyLabel: 'Solar drone',
    bossName: 'Solar Core Guardian',
    terrain: 'solar flare belt',
    difficulty: 1,
  }),
  venus: withMission('venus', {
    title: 'Venus Acid Sky',
    subtitle: 'Bay xuyên tầng mây độc dày đặc',
    background: '/venus/map.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-2.jpg',
    palette: ['#f4d06f', '#a3e635', '#7a4f28'],
    accent: '#ecfccb',
    enemyColor: '#d9f99d',
    bossColor: '#b45309',
    hazardColor: '#bef264',
    shotColors: { scout: '#bef264', scoutAlt: '#fef08a', blade: '#84cc16', heavy: '#f59e0b', boss: '#b45309' },
    enemyLabel: 'Acid wisp',
    bossName: 'Toxic Cloud Queen',
    terrain: 'acid cloud front',
    difficulty: 1.1,
  }),
  earth: withMission('earth', {
    title: 'Earth Blue Defense',
    subtitle: 'Bảo vệ đại dương xanh khỏi rác vũ trụ',
    background: '/earth/map.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-3.jpg',
    palette: ['#38bdf8', '#22c55e', '#f8fafc'],
    accent: '#bbf7d0',
    enemyColor: '#86efac',
    bossColor: '#0ea5e9',
    hazardColor: '#e0f2fe',
    shotColors: { scout: '#22c55e', scoutAlt: '#38bdf8', blade: '#a7f3d0', heavy: '#facc15', boss: '#0ea5e9' },
    enemyLabel: 'Pollution drone',
    bossName: 'Pollution Mothership',
    terrain: 'blue orbit corridor',
    difficulty: 1.05,
  }),
  mars: withMission('mars', {
    title: 'Mars Dust Assault',
    subtitle: 'Chiến đấu giữa bão cát hành tinh đỏ',
    background: '/planets/mars.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-4.jpg',
    palette: ['#fb923c', '#ef4444', '#7c2d12'],
    accent: '#fed7aa',
    enemyColor: '#fdba74',
    bossColor: '#dc2626',
    hazardColor: '#fca5a5',
    shotColors: { scout: '#fb923c', scoutAlt: '#f97316', blade: '#ef4444', heavy: '#fca5a5', boss: '#dc2626' },
    enemyLabel: 'Dust raider',
    bossName: 'Dust War Machine',
    terrain: 'dust storm trench',
    difficulty: 1.2,
  }),
  jupiter: withMission('jupiter', {
    title: 'Jupiter Storm Breaker',
    subtitle: 'Né sét trong vùng Vết Đỏ Lớn',
    background: '/planets/jupiter.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-1.jpg',
    palette: ['#f5c16c', '#f97316', '#fef3c7'],
    accent: '#fde68a',
    enemyColor: '#fde68a',
    bossColor: '#ea580c',
    hazardColor: '#facc15',
    shotColors: { scout: '#fde68a', scoutAlt: '#fbbf24', blade: '#fb923c', heavy: '#f97316', boss: '#ea580c' },
    enemyLabel: 'Storm spark',
    bossName: 'Great Storm Titan',
    terrain: 'great storm stream',
    difficulty: 1.35,
  }),
  saturn: withMission('saturn', {
    title: 'Saturn Ring Clash',
    subtitle: 'Luồn qua vành đai băng đá',
    background: '/planets/saturn.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-2.jpg',
    palette: ['#fde68a', '#c4b5fd', '#94a3b8'],
    accent: '#ddd6fe',
    enemyColor: '#ddd6fe',
    bossColor: '#fbbf24',
    hazardColor: '#e2e8f0',
    shotColors: { scout: '#ddd6fe', scoutAlt: '#c4b5fd', blade: '#fbbf24', heavy: '#f8fafc', boss: '#a78bfa' },
    enemyLabel: 'Ring shard',
    bossName: 'Ring Destroyer',
    terrain: 'ring shard lane',
    difficulty: 1.3,
  }),
  uranus: withMission('uranus', {
    title: 'Uranus Ice Drift',
    subtitle: 'Phá lớp băng methane xanh lạnh',
    background: '/planets/uranus.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-3.jpg',
    palette: ['#a5f3fc', '#67e8f9', '#0e7490'],
    accent: '#cffafe',
    enemyColor: '#cffafe',
    bossColor: '#0891b2',
    hazardColor: '#bae6fd',
    shotColors: { scout: '#67e8f9', scoutAlt: '#a5f3fc', blade: '#22d3ee', heavy: '#e0f2fe', boss: '#0891b2' },
    enemyLabel: 'Ice drone',
    bossName: 'Ice Orbit Warden',
    terrain: 'tilted ice orbit',
    difficulty: 1.45,
  }),
  neptune: withMission('neptune', {
    title: 'Neptune Abyss Tempest',
    subtitle: 'Bắn xuyên biển gió xanh thẳm',
    background: '/planets/neptune.jpg',
    deepSpace: '/missions/shooter/nasa/space-bg-4.jpg',
    palette: ['#60a5fa', '#7c3aed', '#1e3a8a'],
    accent: '#c4b5fd',
    enemyColor: '#93c5fd',
    bossColor: '#4338ca',
    hazardColor: '#818cf8',
    shotColors: { scout: '#60a5fa', scoutAlt: '#a78bfa', blade: '#818cf8', heavy: '#c4b5fd', boss: '#4338ca' },
    enemyLabel: 'Tempest scout',
    bossName: 'Abyss Tempest',
    terrain: 'deep wind tunnel',
    difficulty: 1.55,
  }),
};

export const defaultShooterConfig = planetShooterConfig.earth;
